title: Your awesome title
author: Leo Ayres
email: ayresle000@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Learning github pages. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: __leoayres__ # DO NOT include the @ character, or else the build will fail!
github_username:  l3oayr3s # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
